image: tiangolo/docker-with-compose

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - pip install docker-auto-labels

stages:
  # - test
  - build
  - deploy

# tests:
#   stage: test
#   script:
#     - sh ./scripts/test.sh
#   tags:
#     - build
#     - test

# build-stag:
#   stage: build
#   script:
#     - TAG=stag FRONTEND_ENV=staging sh ./scripts/build-push.sh
#   only:
#     - main
#   tags:
#     - build
#     - test
    
build-prod:
  stage: build
  script:
    - TAG=prod FRONTEND_ENV=production sh ./scripts/build-push.sh
  only:
    - main
#   only:
#     - production
  tags:
    - build
    - test

# deploy-stag:
#   stage: deploy
#   script: 
#     - >
#       DOMAIN=stag.bnbwise.xyz
#       TRAEFIK_TAG=stag.bnbwise.xyz
#       STACK_NAME=stag-bnbwise-xyz
#       TAG=stag
#       sh ./scripts/deploy.sh
#   environment:
#     name: staging
#     url: https://stag.bnbwise.xyz
#   only:
#     - main
#   tags:
#     - swarm
#     - stag

deploy-prod:
  stage: deploy
  script:
    - >
      DOMAIN=bnbwise.xyz
      TRAEFIK_TAG=bnbwise.xyz
      STACK_NAME=bnbwise-xyz
      TAG=prod
      sh ./scripts/deploy.sh
  environment:
    name: production
    url: https://bnbwise.xyz
  only:
    - main
  # only:
  #   - production
  tags:
    - swarm
    - prod
    
