"""Add station model map

Revision ID: 1137e8ddf1d8
Revises: 69233d595a01
Create Date: 2021-08-26 18:10:19.535715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1137e8ddf1d8'
down_revision = '69233d595a01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
