"""Add properties relationship

Revision ID: 4001b9443bb6
Revises: ab383fb06b1c
Create Date: 2021-11-30 19:51:05.496273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4001b9443bb6'
down_revision = 'ab383fb06b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station', sa.Column('property_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'station', 'property', ['property_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'station', type_='foreignkey')
    op.drop_column('station', 'property_id')
    # ### end Alembic commands ###
