"""fix property model

Revision ID: ab383fb06b1c
Revises: 7661e5be45c7
Create Date: 2021-10-13 22:40:12.551830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab383fb06b1c'
down_revision = '7661e5be45c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
