"""fix prop

Revision ID: ca7f379e1058
Revises: 4001b9443bb6
Create Date: 2021-11-30 20:21:26.866582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7f379e1058'
down_revision = '4001b9443bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
